export {default as Navbar } from './Navbar';
export {default as Footer } from './Footer';
export {default as Contact } from './Contact';
export {default as Team } from './Team';
export {default as Home } from './Home';
export {default as Product } from './Product';
export {default as About } from './About';
export { default as Layout } from './Layout';
export { default as Product_Engineer} from './Product_engineer';
export { default as Product_Design} from './Product_design';
